before:
  hooks:
    - go mod download

builds:
  - id: direktion
    main: ./direktion.go
    binary: direktion
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "creekorful/direktion:latest"
      - "creekorful/direktion:{{ replace .Tag \"v\" \"\" }}"
      - "creekorful/direktion:{{ .Major }}"
    skip_push: false

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"

release:
  prerelease: true